/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-MIME.h
 #	source generated by 4D Plugin Wizard
 #	Project : MIME
 #	author : miyako
 #	2021/04/01
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_MIME_H
#define PLUGIN_MIME_H

#include "4DPluginAPI.h"

#include "gmime/gmime.h"
#include "json.h"

typedef struct
{
    Json::Value *json;
    PA_Variable *array_blob;
    const char *name;
    
    GMimeMessage *message;
    int level;
    bool is_main_message;
    
}mime_ctx_simple;

typedef struct
{
    Json::Value *json;
    PA_Variable *array_blob;
    const char *name;
    bool is_top_level;
    
    GMimeMessage *message;
    int level;
    int part_level;
    
    int part;
    bool is_message;
    
}mime_ctx;

#include <mutex>

#if defined(_WIN32)

#define snprintf _snprintf
#define vsnprintf _vsnprintf
#define strcasecmp _stricmp
#define strncasecmp _strnicmp

extern "C" BOOL glib_DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved);
extern "C" BOOL gio_DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved);
extern "C" BOOL gobject_DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved);
#endif

#pragma mark -

#include "C_TEXT.h"
#include "C_LONGINT.h"
#include "C_BLOB.h"

void MIME_PARSE_MESSAGE(PA_PluginParameters params);
void MIME_Create_message(PA_PluginParameters params);

#endif /* PLUGIN_MIME_H */
